services:
  # Backend API Service
  - type: web
    name: walkumentary-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        fromService:
          type: web
          name: walkumentary-backend
          property: port
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: walkumentary-redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: '["https://walkumentary-frontend.vercel.app"]'

  # Redis Cache Service
  - type: redis
    name: walkumentary-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru